font_family             family="Aporetic Sans Mono"
font_size               15.0
disable_ligatures       never
remember_window_size    no
initial_window_width    100c
initial_window_height   36c
confirm_os_window_close 0
window_padding_width 10


# BEGIN_KITTY_THEME
# Adwaita light
include current-theme.conf
# END_KITTY_THEME
