add_newline = false

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[>](bold green)'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[golang]
format = '[ ](bold cyan)'
